// <auto-generated />
namespace ShoppingList_Team2_Master.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ListModelsController : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ListModelsController));
        
        string IMigrationMetadata.Id
        {
            get { return "201609072004159_ListModelsController"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
